### ISSUE TITLE
Plugin StaffPlus v1.16.49 generated an exception while executing task 556

### ISSUE THREAD

**Issue by TGTGamer** [garagepoort/StaffPlusPlus#142]
Heya, I'm getting some errors when attempting to use this application with SpigotPaper 1.16.5 using MySQL synchronisation

```
02.03 11:17:17 [Server] WARN [StaffPlus] Plugin StaffPlus v1.16.49 generated an exception while executing task 556
02.03 11:17:17 [Server] INFO java.lang.RuntimeException: java.sql.SQLException: No value specified for parameter 1
02.03 11:17:17 [Server] INFO at net.shortninja.staffplus.staff.warn.warnings.database.AbstractSqlWarnRepository.expireWarnings(AbstractSqlWarnRepository.java:162) ~[?:?]
02.03 11:17:17 [Server] INFO at net.shortninja.staffplus.staff.warn.warnings.WarnService.lambda$expireWarnings$7(WarnService.java:145) ~[?:?]
```

Here's my config:
```yml
# Staff++ | Made with love by Shortninja and continued by Qball - Revisited by Garagepoort
# 
# If you're having trouble with item type names, refer to here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# All item slots are how they "should be", meaning the first slot of an inventory will be one. Maximum is 36.

staff-mode:
  cps-module:
    lore: '&7Runs a click per second test on, &7the player that was clicked.'
    item: CLOCK
    enabled: true
    max: 16.0
    slot: 7
    name: '&3CPS'
    time: 10
  gui-module:
    name: '&eGUI Hub'
    miner-name: '&bMiner GUI'
    reports-title: '&bUnresolved reports'
    miner-title: '&bUnderground users'
    slot: 4
    closed-reports-title: '&bClosed reports'
    mute-gui: true
    mute-lore: '&7Shows all currently muted players.'
    mute-title: '&bOverview muted players'
    ban-name: '&bBanned players GUI'
    protected-areas-gui: true
    reports-name: '&bUnresolved reports GUI'
    miner-lore: '&7Shows all players under the set Y value.'
    xray-level: 16
    reports-lore: '&7Shows all open reports.'
    protected-areas-title: '&bOverview protected areas'
    protected-areas-name: '&bProtected Areas GUI'
    my-reports-lore: '&7Shows reports currently assigned to you.'
    miner-gui: true
    ban-title: '&bOverview banned players'
    protected-areas-lore: '&7Shows all currently set protected areas.'
    reports-gui: true
    ban-gui: true
    mute-name: '&bMuted players GUI'
    ban-lore: '&7Shows all currently banned players.'
    closed-reports-lore: '&7History of all closed reports.'
    lore: '&7Opens the GUI hub.'
    my-reports-title: '&bReports assigned to you'
    enabled: true
    item: PAPER
  vanish-module:
    lore: '&7Toggles your total vanish.'
    item: INK:10
    slot: 3
    name: '&6Vanish'
    item-off: INK:8
    enabled: true
  freeze-module:
    item: BLAZE_ROD
    lore: '&7Toggles freeze for the clicked player.'
    chat: true
    slot: 6
    prompt: false
    sound: ORB_PICKUP
    name: '&2Freeze'
    damage: false
    prompt-title: '&bFrozen'
    enabled: true
    logout-commands: ban %player%
    timer: 5
  inventory-interaction: true
  invincible: true
  random-teleport-module:
    item: ENDEREYE
    lore: '&7Teleports you to a random player.'
    name: '&cRandom Teleport'
    enabled: true
    slot: 2
    random: false
  vanish-type: TOTAL
  follow-module:
    item: LEAD
    slot: 9
    name: '&9Follow'
    lore: '&7Mounts the player that was clicked.'
    enabled: true
  examine-module:
    lore: '&7Inspects the inventory of the player that was clicked.'
    info-line:
      notes: 7
      food: 1
      infractions: 5
      gamemode: 4
      location: 6
      warn: 9
      ip-address: 2
      ping: 3
      freeze: 8
    item: CHEST
    title: '&bExamine inventory'
    enabled: true
    name: '&bExamine'
    slot: 8
  enable-on-login: false
  creative: true
  counter-module:
    lore: '&7Shows all staff online and in staff mode'
    item: HEAD
    slot: 5
    title: '&bCurrent staff online'
    name: '&aStaff List'
    show-staff-mode: false
    enabled: true
  compass-module:
    velocity: 5
    slot: 1
    lore: '&7Launches you towards the, &7location you are facing.'
    enabled: true
    name: '&4Launcher'
    item: COMPASS
  silent-chest-interaction: true
  hunger-loss: false
  damage: false
  enable-commands: example1 %player%, example2 %player%
  disable-on-world-change: false
  staff-see-staff-in-mode: true
  item-pickup: true
  disable-on-logout: true
  original-location: false
  flight: true
  disable-commands: example1 %player%, example2 %player%
  item-drop: false
  block-manipulation: false
commands:
  changePass: changepassword
  reports:
    manage:
      gui: manage-reports
      cli: reports
  my-reports: my-reports
  login: login
  staff-list: personnel
  infractions-top-view: infractions-top
  warnings:
    manage:
      gui: manage-warnings
      appealed-gui: manage-appealed-warnings
  infractions-view: infractions
  protect-area: protectArea
  freeze: freeze
  cps: cps
  alt-detect-whitelist: altWhitelist
  resetPass: resetPassword
  kick: kick
  strip: strip
  echest_view: eview
  broadcast: broadcast
  protect-player: protectPlayer
  mute: mute
  staff-mode: staff
  follow: follow
  register: register
  chat: chat
  ban: ban
  tempban: tempban
  my-warnings: my-warnings
  vanish: vanish
  teleport-to-location: teleportToLocation
  clearInv: clear
  teleport-back: teleportBack
  warns: warns
  unban: unban
  warn: warn
  ticket: ticket
  trace: trace
  notes: notes
  alerts: alerts
  tempmute: tempmute
  teleport-to-player: teleportToPlayer
  revive: revive
  report: report
  unmute: unmute
  reportPlayer: reportPlayer
  staff-chat: sc
  examine: examine
  teleport-here: teleportHere
storage:
  type: 'mysql'
  mysql:
    host: 'mcdbs.ggservers.com'
    user: 'user_154315'
    database: 'user_154315'
    password: '[redacted]'
    port: 3306
server-sync-module:
  staffmode-sync: false
  report-sync: true
  ban-sync: true
  warning-sync: true
  kick-sync: true
  mute-sync: true
  vanish-sync: true
permissions:
  enderchests:
    interact: staff.enderchests.interact
    view:
      online: staff.enderchests.view.online
      offline: staff.enderchests.view.offline
  reports:
    manage:
      accept: staff.reports.manage.accept
      resolve: staff.reports.manage.resolve
      delete: staff.reports.manage.delete
      teleport: staff.reports.manage.teleport
      reject: staff.reports.manage.reject
      view: staff.reports.manage.view
  mute-bypass: staff.staffplus.mute-bypass
  examine-view-inventory:
    offline: staff.examine.view-inventory-offline
    online: staff.examine.view-inventory
  warnings:
    manage:
      expire: staff.warnings.manage.expire
      view: staff.warnings.manage.view
      delete: staff.warnings.manage.delete
    appeals:
      notifications: staff.warnings.appeals.notifications
      approve: staff.warnings.appeals.approve
      create-others: staff.warnings.appeals.create.others
      reject: staff.warnings.appeals.reject
      create: staff.warnings.appeals.create
  name-change: staff.alerts.namechange
  compass: staff.compass
  vanish: staff.vanish
  gui: staff.gui
  ipPerm: staff.staffplus.hideip
  follow: staff.follow
  teleport-here: staff.teleport-here
  counter: staff.counter
  counter-show-vanished: staff.counter-show-vanished
  alt-detect-bypass: staff.staffplus.alt-detect-bypass
  protect-player: staff.staffplus.protect-player
  report-update-notifications: staff.report.update.notifications
  alt-detect-whitelist: staff.staffplus.alt-detect-whitelist
  trace: staff.trace
  report-bypass: staff.report.bypass
  invClear: staff.staffplus.clearinv
  tickets: staff.tickets
  random-teleport: staff.random-teleport
  revive: staff.revive
  trace-bypass: staff.trace.bypass
  teleport-to-player: staff.teleport-to-player
  report: staff.report
  cps: staff.cps
  chat-clear: staff.chat.clear
  warn-bypass: staff.warn.bypass
  staff-chat: staff.staffchat
  mode-silent-chest-interaction: staff.mode.silent-chest-interaction
  examine: staff.examine
  broadcast: staff.staffplus.broadcast
  alerts-alt-detect: staff.alerts.alt-detects
  staffplus: staff.staffplus
  xray: staff.alerts.xray
  kick-bypass: staff.staffplus.kick-bypass
  lockdown: staff.lockdown
  chat-slow: staff.chat.slow
  blacklist: staff.blacklist
  resetPass: staff.staffplus.resetpassword
  infractions:
    view: staff.infractions.view
  protect-area: staff.staffplus.protect-area
  teleport-bypass: staff.teleport.bypass
  wild-card: staff.*
  vanish-total: staff.vanish.total
  tp: staff.tp
  unmute: staff.staffplus.unmute
  unban: staff.staffplus.unban
  ban-bypass: staff.staffplus.ban-bypass
  invClear-bypass: staff.staffplus.clearinv-bypass
  mode: staff.mode
  freeze-bypass: staff.freeze.bypass
  mention: staff.alerts.mention
  alerts: staff.staffplus.alerts
  strip: staff.strip
  mute: staff.staffplus.mute
  member: staff.member
  kick: staff.staffplus.kick
  teleport-to-location: staff.teleport-to-location
  vanish-list: staff.vanish.list
  warn: staff.warn
  view-my-reports: staff.report.view-my-reports
  freeze: staff.freeze
  examine-inventory-interaction:
    online: staff.examine.inventory-interaction
    offline: staff.examine.inventory-interaction-offline
  view-my-warnings: staff.warn.view-my-warnings
  chat-toggle: staff.chat.toggle
  ban: staff.staffplus.ban
  block: staff.block
chat-module:
  slow: 5
  blacklist-module:
    character: '*'
    enabled: false
    allowed: bypass, assembly, assassin, compass, assume, assault, asset, assort
    merging: true
    periods: (), (dot),
    characters: 卐, 卍
    words: fuck, shit, ass, bitch, dick, cock, piss, cunt, fag, faggot, slut, nigger,
      nigga
    hoverable: false
    domains: com, net, org
  enabled: true
  lines: 100
mute-module:
  enabled: true
infractions-module:
  bans-gui-item: PAPER
  mutes-gui-item: PAPER
  enabled: true
  show-mutes: true
  kicks-gui-item: PAPER
  show-reported: true
  show-bans: true
  warnings-gui-item: PAPER
  show-warnings: true
  reported-gui-item: PAPER
  show-kicks: true
reports-module:
  reporter-notifications:
    notify-on-join: true
    status-change-notifications: IN_PROGRESS;RESOLVED;REJECTED
  cooldown: 10
  closing-reason-enabled: true
  show-reporter: true
  enabled: true
  sound: ORB_PICKUP
vanish-module:
  vanish-message-enabled: true
  suggestions: true
  tab-list: true
  show-away: false
  chat: true
  enabled: true
metrics: true
alerts-module:
  xray-alerts:
    blocks: SPAWNER, EMERALD_ORE, DIAMOND_ORE, GOLD_ORE, IRON_ORE, COAL_ORE, LAPIS_ORE,
      REDSTONE_ORE
    enabled: true
  mention-notify: true
  alt-detect-notify:
    trust-levels: FAIRLY_POSITIVE;POSITIVE
    enabled: true
  name-notify: true
  sound: ORB_PICKUP
warnings-module:
  user-notifications:
    enabled: true
    always-notify: false
  thresholds:
  - score: 13
    actions:
    - command: ban %player% &4Warning threshold has been met
      run-strategy: ALWAYS
  severity-levels:
  - name: MINOR
    score: 1
    expiresAfter: 1 WEEK
  - name: MAJOR
    score: 3
    expiresAfter: 1 MONTH
  - name: CRITICAL
    score: 5
  actions: []
  sound: ORB_PICKUP
  show-issuer: true
  enabled: true
  appeals:
    reasons:
    - ''
    enabled: true
    fixed-reason: true
    resolve-reason-enabled: true
sound-names: random.chestopen, random.chestclosed
blocked-mode-commands: /example1, /example2, /example3
protect-module:
  area-max-size: 40
  player-enabled: true
  area-enabled: true
glass-title: '&bChoose GUI glass color'
glass-color: 0
alt-detect-module:
  enabled: true
staff-chat-module:
  handle: '@'
  enabled: true
  bungee: true
main-world: world
clock: 2
offline-players-mode: true
trace-module:
  enabled: true
  trace-events: PICKUP_ITEM;DROP_ITEM;BLOCK_BREAK;BLOCK_PLACE;COMMANDS;CHAT;WORLD_CHANGE;INVENTORY;DAMAGE
  output-channels: CHAT;FILE
blocked-commands: /example1, /example2, /example3
lang: lang_en
ban-module:
  enabled: true
enderchest-module:
  enabled: true
broadcast-module:
  enabled-servers: CURRENT
  enabled: true
timestamp-format: dd/MM/yyyy-HH:mm:ss
animation-packets: PacketPlayOutBlockBreakAnimation, PacketPlayOutBlockAction
auto-save: 3602
server-name: MC1
authentication:
  provider: noop
config-version: 6205
kick-module:
  enabled: true
```
