### ISSUE TITLE
refactor: rebuild the config based on rank system

### ISSUE THREAD

**Issue by TGTGamer** [garagepoort/StaffPlusPlus#146]
Pretty simple, as discussed on call @garagepoort 

```yml
   builder: 
      permission: 'staff.builder'
      weight: 1
      gui: 
        - compass-module:1
        - vanish-module:2
        - counter-module:3
      block-manipulation: true
      inventory-interaction: true
    Admin:
      permission: 'staff.admin'
      weight: 3
      gui:
      - compass-module:1
      - vanish-module:3
      - gui-module:2
      - examine-module:8
      - follow-module:9
 ```
