### ISSUE TITLE
refactor: api for discord templates

### ISSUE THREAD

**Issue by TGTGamer** [garagepoort/StaffPlusPlus#147]
I want to suggest changing the names for the API to the following to standardise the entire thing, making it easier to create templates. 

```yml
eventName:
  target:
    - name
    - Uuid
    - matchedName
    - matchedUuid
  
  staff:
    - name
    - uuid
  
  reason: 
    - created
    - resolved
   
  warnings:
    - severity
    - staff
    - reason 

  details: 
    - endDate
    - type
    - status
    - location
    - serverName
    - thresholdScore
    - commandsTriggered
    - severity

example usage: 
  bans.reason.created
  warnings.target.name
```

This is broken down and made up from the following spec:
```yml
altdetects: 
  - target:
    # general
    - name # user who was checked for matches (replaces checkedName)
    - uuid # (replaces checkedUuid)

    # alt detect
    - matchedName # user who matched with another player
    - matchedUuid # Uuid for above user

appeals: 
  - target:
    - name # user who is appealing (replaces appealerName)
    - uuid # (replaces appealerUuid)

  staff: 
    - name # the user who is taking this action (replaces resolverName)
    - uuid # (replaces resolverUuid)

  - reason:
    - created # the reason for the appeal when it was opened (replaces reason)
    - resolved # the reason for resolving the appeal (replaces resolveReason.get())
  
  - warnings: 
    - severity # the severity of latest warning
    - staff    # the staff member who issued warning
    - reason   # the reason for warning

bans: 
  - target:
    - name # user who is banned (replaces targetName)
    - uuid # (replaces targetUuid)

  staff: 
    - name # the user who is taking this action (replaces issuerName)
    - uuid # (replaces issuerUuid)

  - reason:
    - created # the reason for the ban when it was issued (replaces reason)
    - resolved # the reason for unbanning the user (replaces unbanReason)
  
  - details: 
    - endDate # same as previous versions

kicks: 
  - target:
    - name # user who is kicked (replaces targetName)
    - uuid # (replaces targetUuid)

  staff: 
    - name # the user who is taking this action (replaces issuerName)
    - uuid # (replaces issuerUuid)

  - reason:
    - created # the reason for the ban when it was issued (replaces reason)
    - resolved # the reason for unbanning the user (replaces unbanReason)

mutes: 
  - target:
    - name # user who is muted (replaces targetName)
    - uuid # (replaces targetUuid)

  staff: 
    - name # the user who is taking this action (replaces issuerName)
    - uuid # (replaces issuerUuid)

  - reason:
    - created # the reason for the ban when it was issued (replaces reason)
    - resolved # the reason for unbanning the user (replaces unbanReason)
  
  details: 
    - endDate # same as previous versions

reports: 
  - target:
    - name (replaces reporterName)
    - uuid
  
  - culprit:
    - name (replaces culpritName)
    - uuid
  
  - reason:
    - created (replaces reason)
    - resolved (replaces closeReason)

  details: 
    - type (not implemented yet?!)
    - status (replaces reportStatus)
    - location (replaces location)

staffmode: 
  - staff:
    - name # (replace playerName)
    - uuid
  
  details:
    - serverName
    - location


threshold: 
  - target: 
    - name # (replaces playerName)
    - uuid

  details:
    - thresholdScore
    - commandsTriggered
  
warnings:
  - target:
    - name (replaces reporterName)
    - uuid

  - staff:
    - name # (replace playerName)
    - uuid

  - reason:
    - created (replaces reason)

  - details: 
    - severity
 ```
