### ISSUE TITLE
Staff Chat turning on when the word "sc" is mentioned in chat

### ISSUE THREAD

**Issue by amouranthtoo** [garagepoort/StaffPlusPlus#170]
Staff Chat turning on when the word "sc" is mentioned in chat
Basicly so whenever i say screen itl send reen to staffchat for some odd reason idk why

**Comment by garagepoort** [comment]
Hey @Angelic-System 
Can you share the staffchat-module configuration part?

**Comment by Angelic-System** [comment]
im not the owner of the server unfortunalty

**Comment by garagepoort** [comment]
Ok just make sure that inside the config the `handle` is not set to `sc`

It should look something like this:
```
  channels:
      - command: sc
        handle: "@"
        name: staffchat
        prefix: '&dStaffChat &8»'
        message-format: '&b%player% &8» &7%message%'
        permission: staff.staffchat
```
