### ISSUE TITLE
Item pickug, Exp grab while vanish

### ISSUE THREAD

**Issue by LuluxClient** [garagepoort/StaffPlusPlus#188]
Hello I have "item-pickup" to false but I can still pick up items, here is my config:

```
modes:
  default:
    block-manipulation: true
    inventory-interaction: true
    silent-chest-interaction: true
    item-drop: true
    item-pickup: false
    vanish-type: TOTAL
    invincible: true
    damage: false
    hunger-loss: false
    flight: true
    creative: false
    night-vision: false
    original-location: false
    enable-on-login: true
    disable-on-logout: false
    enable-commands: []
    disable-commands: []
    disable-on-world-change: false
    gui:
    - compass-module:1
    - random-teleport-module:2
    - vanish-module:3
    - gui-module:4
    - counter-module:5
    - freeze-module:6
    - cps-module:7
    - examine-module:8
    - follow-module:9
    - player-details-module:10

```
