### ISSUE TITLE
Staffchat Module will not disable

### ISSUE THREAD

**Issue by FastQuack** [garagepoort/StaffPlusPlus#223]
Setting line 106 of config.yml to false and restarting the server does not disable the staff-chat functionality.

```
staff-chat-module:
  # Whether or not the plugin will use "/sc" features.
  enabled: false
  # Whether or not the plugin synchronises staff chat across the bungee network
  bungee: true
  
  # The string that can be used at the beginning of a message to make it appear in staff chat.
  # If you have "@" as your string, typing "@hey guys" would send "hey guys" to staff chat.
  # Leave blank to disable.

  channels:
  - command: sc
    handle: '@'
    name: staffchat
    prefix: '&dStaffChat &8»'
    message-format: '&b%player% &8» &7%message%'
    permission: staff.staffchat
    sound: NONE
```
