### ISSUE TITLE
Cannot disable joinmessages-module

### ISSUE THREAD

**Issue by Partizionare** [garagepoort/StaffPlusPlus#230]
```
joinmessages-module:
  # Whether or not the plugin will use "/mute player" features.
  enabled: false
  messages:
  - permission: staff.joinmessages.staff
    message: '&6[Staff] &4%player% &7has joined.'
    weight: 1
```

Hello, I cannot disable this joinmessages-module.
After rebooting many times, the messages is still showing.

Server details:
- Purpur
- Version 1.20.1

Also notice that the config.yml 
"# Whether or not the plugin will use "/mute player" features." is a repetitio of another module, and doesn't contains the infos about joinmessages-module
